name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check_app:
    runs-on: ubuntu-latest
    steps:
    - name: clone_project
      uses: actions/checkout@v3
    - name: prepare_env
      run: |
        sudo apt update
        sudo apt install gcc-multilib g++-multilib
    - name: compile
      run: make
    - name: append_path
      run: echo "`pwd`/bin" >> $GITHUB_PATH
    - name: compile_tests
      run: make test
    - name: run_tests
      run: |
        for i in $(seq 1 1 `ls ./test/bin | wc -l`)
        do
          echo "Starting test n°$i"
          hadesdbg ./test/bin/test_$i -script ./test/scripts/test_$i.hscript -output ./test_$i.hout -entry 0x1040 -bp 0x1131:15
          if [[ $(md5sum ./test_$i.hout | cut -d' ' -f1) == $(md5sum ./test/results/test_$i.hout | cut -d' ' -f1) ]]
          then
            echo "Success !"
          else
            echo "Failure !"
            echo "Content of result file :"
            cat ./test_$i.hout
            exit 1
          fi
        done
